
    # AT&T: number@txt.att.net (SMS), number@mms.att.net (MMS)
    # T-Mobile: number@tmomail.net (SMS & MMS)
    # Verizon: number@vtext.com (SMS), number@vzwpix.com (MMS)
    # Sprint: number@messaging.sprintpcs.com (SMS), number@pm.sprint.com (MMS)
    # Xfinity Mobile: number@vtext.com (SMS), number@mypixmessages.com (MMS)
    # Virgin Mobile: number@vmobl.com (SMS), number@vmpix.com (MMS)
    # Tracfone: number@mmst5.tracfone.com (MMS)
    # Simple Mobile: number@smtext.com (SMS)
    # Mint Mobile: number@mailmymobile.net (SMS)
    # Red Pocket: number@vtext.com (SMS)
    # Metro PCS: number@mymetropcs.com (SMS & MMS)
    # Boost Mobile: number@sms.myboostmobile.com (SMS), number@myboostmobile.com (MMS)
    # Cricket: number@sms.cricketwireless.net (SMS), number@mms.cricketwireless.net (MMS)
    # Republic Wireless: number@text.republicwireless.com (SMS)
    # Google Fi (Project Fi): number@msg.fi.google.com (SMS & MMS)
    # U.S. Cellular: number@email.uscc.net (SMS), number@mms.uscc.net (MMS)
    # Ting: number@message.ting.com
    # Consumer Cellular: number@mailmymobile.net
    # C-Spire: number@cspire1.com
    # Page Plus: number@vtext.com

    Sender: 'EXAMPLE@gmail.com'
    Sender_Pass: 'EMAIL-PASSWORD'

    Chrome_Driver: /usr/bin/chromedriver
    Attachment_Path: attachments/

    Phone_Number: '1234567890'
    Attachments: 'Fat guys'
    Number_Of_MSGs: 10
